# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'A2ISurveySample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for A2ISurvey
pod 'A2ISurveyFramework', :git => 'https://github.com/a2ianalytics/a2i-survey-ios-sdk.git', :tag => '0.0.1'

end
